### ISSUE TITLE
add individual scales and colors to each heatmap

### ISSUE THREAD

**Issue by fidelram** [fidelram/deepTools#109]
The idea is to get something like this from Gilsbach, R., Preissl, S., Grüning, B. a., Schnick, T., Burger, L., Benes, V., … Hein, L. (2014). Dynamic DNA methylation orchestrates cardiomyocyte development, maturation and disease. Nature Communications, 5(May), 5288. doi:10.1038/ncomms6288:

![image](https://cloud.githubusercontent.com/assets/4964309/10687242/eb835330-796b-11e5-83e0-a071b47fc282.png)

**Comment by dpryan79** [comment]
Maybe we should talk about this when I'm back in the office on Friday. I was playing around with this and more or less implemented all of it. However, the colorbar becomes an issue. We basically need to start adding color bars for each plot, likely below the heatmap like in the example. Then the question arises as to whether to always put the color bar down there, to always put it under each sample, and whether things should be treated differently if a colormap is used multiple times. Then, of course, there's the question of what to do when `--perGroup` is then used. Actually including that is going to lead to an explosion of feature creep that I don't think (A) will be used often and (B) will be non-trivial to maintain and test for correctness. In addition, specifying a list of colormaps is easy enough, but to do something like what you showed you'd need to instead specify multiple color lists...which would likely become a hack involving custom delimiters.

For those reasons, I'd suggest closing this and advising those who want to create highly customized stuff like this to take the matrix generated by comuteMatrix and just write a bit of python to do what they want. Otherwise we're quickly going to end up incorporating a hundred more options in.

**Comment by friedue** [comment]
I don't completely get the point of why one would need to generate multiple plots with vastly differing scales in one go? 
one could simply run computeMatrix/plotHeatmap on the samples individually...the only reason why one would opt for the all-at-once-option is because of the clustering, but that should be done with caution anyway if the samples have very different ranges. most likely, the clustering is going to be dominated by the one sample with the largest spread of values anyway.

**Comment by fidelram** [comment]
PR #338 addresses the issue. For examples see: http://deeptools.readthedocs.org/en/develop/content/tools/plotHeatmap.html

**Comment by dpryan79** [comment]
Did you update the Galaxy wrapper?

**Comment by fidelram** [comment]
This is an example of how the new heatmaps look

![color_example](https://cloud.githubusercontent.com/assets/4964309/14746314/4f893192-08af-11e6-8509-986db63ebd5c.png)

**Comment by fidelram** [comment]
The boxes can be removed if needed. 

![example2](https://cloud.githubusercontent.com/assets/4964309/14746378/957f7d32-08af-11e6-9cdd-8d564aabc728.png)

**Comment by friedue** [comment]
is this the next design award in the making? ;) 
looks great!
