### ISSUE TITLE
Allow for user-defined sample size in bamPEFragmentSize

### ISSUE THREAD

**Issue by asrichter** [fidelram/deepTools#137]
Currently bamPEFragmentSize uses a non-specified number of samples fragments to estimate the fragment size.
One should provide an option to allow for user-defined sample size (as in e.g. bamCorrelate) and also specify the default sample size.

**Comment by vivekbhr** [comment]
The sample size depends on numProcessors and genome size at this moment.. I added a better explanation for this now but custom sample size is still not implemented.

**Comment by dpryan79** [comment]
There's no good way to do this. How this works is that the genome is divided into chunks based on the number of processors and files being used with a max of 100kb (as @vivekbhr said), but then only the reads in or spanning the first 50kb are used for the stats. The number of reads sampled is whatever this happens to be...so with the identical settings it'll end up varying by file.

I imagine that this can get really excessive in high coverage files, so I would propose either adding an option to set the genome chunk size or the bin size within the chunks. It'd personally prefer making the bin size modifiable (both because it has an actual default and because it's vastly easier to describe!). But obviously if someone has a better idea then we can go with that :)

**Comment by fidelram** [comment]
For other tools (e.g multiBamSummary) we use the distance between bins as a way to determine the number of samples and the bin size. We can simply use the same set of parameter.

**Comment by dpryan79** [comment]
That'd work too

**Comment by dpryan79** [comment]
Have a look at #279, which is still a bit of a work in progress. I just made things similar to multiB*Summary. A bit of testing suggests similar number of reads sampled. Note that this will obviously affect every tool that uses fragment length estimates.

**Comment by dpryan79** [comment]
#279 is ready to go if anyone has any last comments.

**Comment by asrichter** [comment]
Is the fragment size estimation actually spliced-read-aware, i.e. can it handle RNA-seq data?

**Comment by dpryan79** [comment]
Jein. It's perfectly happy with spliced reads, but they slightly inflate the estimate. For this reason, you'll find that the median is more useful than the mean.

**Comment by dpryan79** [comment]
I should note that I test this on our RNAseq dataset.

**Comment by asrichter** [comment]
So does this mean that the size of the insertion, e.g. the intron, is included in the fragment size estimate?

**Comment by dpryan79** [comment]
Yes, this is true for all tools that use a fragment size within deeptools. Again, either just use the median or I suppose we could filter out spliced reads.

**Comment by steffenheyne** [comment]
split reads are not the problematic ones, I think, only those reads where eg. the end of R1 and start of R2 are on different exons. Here the actual transcript length in between counts and not the "genomic" distance including the intron....or?

**Comment by dpryan79** [comment]
True, though again one just uses the median then.

**Comment by asrichter** [comment]
Ah, Steffen is right. Both reads (split-reads) and fragments spanning multiple exons are problematic
Then we should generally use the median and not the mean for all deepTools fragment size estimates, right? Is this already the case?

**Comment by steffenheyne** [comment]
...and there is no way to identify such reads from the bam file only, isn't it?

**Comment by dpryan79** [comment]
Correct, I'll check whether we're using mean or median. No, there's no way to reliably filter them out, since inevitably someone will use mate-pairs as input at some point.

**Comment by asrichter** [comment]
I don't think so, you have to map to the transcriptome then.

**Comment by fidelram** [comment]
As @steffenheyne said,  filtering spliced reads will not solve the problem for RNAseq data because PE pairs can lie in different exon.

However, I would say that PE fragment length should not be used for RNA-seq data. The computation of the distance is only done when read extension is required and the data is PE.

**Comment by dpryan79** [comment]
@fidelram: It's convenient to get the insert size, at which point the median is a good enough metric already.

@asrichter I checked and we already only ever use the median for things.

If there aren't any other issues then I'll go ahead and merge and close this.

**Comment by asrichter** [comment]
Fine for me.

**Comment by YichaoOU** [comment]
Hello,

Is dividing the genomes into chunks solely for the multi-processing purpose? Why don't we just use all the PE read fragment length from the bam file to make a fragment length distribution?

Thanks,
Yichao
