### ISSUE TITLE
Testing Docker Image

### ISSUE THREAD

**Issue by bgruening** [fidelram/deepTools#157]
The Docker image with the latest wrapper can be tested in 10min with this command. I hope everything will work, let me know if now. This is not the final version but a version we can test and work with, hopefully.

`docker run -i -t -p 8080:80 bgruening/galaxy-deeptools`

**Comment by dpryan79** [comment]
FYI, I'm testing this now. Once the server is up and accessible from outside I'll send you a link.

**Comment by dpryan79** [comment]
I do get an error of some sort immediately after the containers are downloaded:

    umount: /var/lib/docker: must be superuser to umount
    Traceback (most recent call last):
      File "/usr/bin/ansible", line 36, in <module>
        from ansible.runner import Runner
    ImportError: No module named ansible.runner

This doesn't seem to have an actual effect, though.

**Comment by bgruening** [comment]
Yeah, does not affect the container ... we are running all on dev ;)

**Comment by dpryan79** [comment]
Hmm, by default it can't run any jobs or take uploaded files, since it can't connect to a slurm server

**Comment by dpryan79** [comment]
I should note that this just requires changing job_conf.xml, which is quite simple. I'm not sure why slurmd isn't running, perhaps because I'm using `--net=host` that's causing problems (I'm not sure if it's running on the host server or not, but obviously that'd be a problem).

**Comment by bgruening** [comment]
Maybe I should build against the stable version :)
But this seems wired too me because starting it in a normal way everything starts up perfectly fine.

**Comment by dpryan79** [comment]
I still haven't figured out why yet, but it seems that bx-python needs to be the last thing prepended to the PYTHONPATH. If that's not the case, its `site.py` doesn't get run and the egg directories are ignored (i.e., you can't `import bx` any more, which then causes some of the deepTools tools to not work). A work around is to just reorder things so that the bx-python env.sh is the last one sourced, but I'm still working on figuring out exactly why this is happening, since I'd prefer to just fix that.

**Comment by bgruening** [comment]
@dpryan79 when did this happen at program start or does the program calculate and crashes at the end?

**Comment by dpryan79** [comment]
@bgruening At start. I can also confirm this by sourcing `env.sh` within deeptools, starting python and entering `import bx`.

**Comment by dpryan79** [comment]
@bgruening: I figured out why this is happening. bx-python is installed as an egg rather than as a regular module. Eggs are *only* loaded if they're in `site-packages` (e.g., they come with python) or if there's a `site.py` in the first entry in `sys.path`. The latter will only happen if the whatever directory that is happens to contain eggs. Since most python packages, such as scipy/numpy/pybigwig/deepTools, don't get installed as eggs, then if they're the first entry in `sys.path` all python package installed as eggs from the tool shed will get ignored.

I imagine that this sort of issue is encountered frequently in galaxy, so perhaps there's a known fix.

**Comment by dpryan79** [comment]
@bgruening: On second thought, an easy enough work-around is to just have bx-python add its egg to PYTHONPATH. I'll make a PR with the IUC.

**Comment by dpryan79** [comment]
PR is here: https://github.com/galaxyproject/tools-iuc/pull/502

**Comment by bgruening** [comment]
Very interesting! I have no clue why bx-python is build as egg and all other packages aren't.
Updated and merged all packages into the TS.
