### ISSUE TITLE
computeMatrix: advanced output settings

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#179]
one of the "advanced output" is now very purpose of the tool (matrix of values).
Not sure if the other outputs (profile data and regions after skipping) are still reported.

**Comment by bgruening** [comment]
@thomasmanke I don't understand this, sorry. What do you want to have changed?

**Comment by dpryan79** [comment]
I would label this "wontfix". The matrix of values as a text file is almost never useful to a galaxy user, it should be disabled by default (as it currently is) and hidden by default (also as it currently is).

**Comment by thomasmanke** [comment]
?? computeMatrix computes a matrix, but currently this is advanced output and disabled. I think I'm missing something.

**Comment by dpryan79** [comment]
No, it always computes a matrix, the question is whether a text file representation is saved. Perhaps the help there should be updated.

**Comment by thomasmanke** [comment]
Ah: Plain vs. compressed! ok then. yes, a comment would be nice

**Comment by vivekbhr** [comment]
@dpryan79 you probably have to restart the docker after this mere since this is not working yet..

**Comment by bgruening** [comment]
I'm creating a new image right now.

**Comment by dpryan79** [comment]
@vivekbhr: I'll update the wrappers and install now. FYI, the general workflow is as follows:

1. Some change is merged into the release-1.6 branch
2. Björn or I trigger a docker image build.
3. The aforementioned step has a "side effect" of pushing updated wrappers to the Galaxy toolshed.
4. I manually install those on deeptools2
5. Often I restart, since that's typically needed.

Not exactly automatic, but that's good :)

**Comment by dpryan79** [comment]
Restarted, this should work now.
