### ISSUE TITLE
Include Galaxy wrapper testing in travis

### ISSUE THREAD

**Issue by bgruening** [fidelram/deepTools#183]
Do we want this? The only disadvantage I can see is that testing keeps longer.

**Comment by dpryan79** [comment]
I guess it depends on how long the additional testing takes.

**Comment by bgruening** [comment]
planemo t .  337,14s user 37,15s system 96% cpu 6:26,96 total

**Comment by dpryan79** [comment]
So maybe 8-9 minutes total then as opposed to 3 or so. I'm OK with that, for whatever that's worth.

**Comment by bgruening** [comment]
To test the wrappers ;) and to get informed if we change the CLI interface but not the wrappers.

**Comment by dpryan79** [comment]
I have a PR ready that does this. It generally works OK, though there seems to be a race condition for access to the sqlite database causing things to randomly fail due to Galaxy not being able to get a lock (I don't know of a way to get around this).

Nonetheless, this seems to work well enough, we just need to rerun a failed test on occasion...which is better than no testing at all.

**Comment by bgruening** [comment]
Great work @dpryan79!
