### ISSUE TITLE
multiBamCoverage produces corrupted output in --outRawCounts

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#228]
The corrupted format below (EOL problem) occurs reproducibly.

maximus:~manke/tools/deepTools_test/test02>   ./test02.sh 
maximus:~/tools/deepTools_test/test02>   head -309780 bamcov.32333.tab | tail -10
GL000219.1	20000	30000	0.0	0.0	0.0	0.0	0.0	0.0
GL000219.1	30000	40000	0.0	0.0	0.0	0.0	0.0	0.0
GL000219.1	40000	50000	0.0	0.0	0.0	0.0	0.0	0.0
GL000219.1	50000	60000	0.0	0.0	0.0	0.0GL000219.1	80000	90000	0.0	0.0	0.0	0.0	0.0	0.0
GL000219.1	90000	100000	0.0	0.0	0.0	0.0	0.0	0.0
GL000219.1	100000	110000	0.0	0.0	0.0	0.0	0.0	0.0
GL000219.1	110000	120000	0.0	0.0	0.0	0.0	0.0	0.0
GL000219.1	120000	130000	0.0	0.0	0.0	0.0	0.0	0.0
GL000219.1	130000	140000	0.0	0.0	0.0	0.0	0.0	0.0
GL000219.1	140000	150000	0.0	0.0	0.0	0.0	0.0	0.0

**Comment by dpryan79** [comment]
In other words, `multiBamCoverage bins  -bs 10000 -b some_bam_files -out blah.npz --outRawCounts bamcov.32333.tab` is doing that.

**Comment by fidelram** [comment]
I just tested and the problem is this line https://github.com/fidelram/deepTools/blob/master/deeptools/countReadsPerBin.py#L281

```shutil.copyfileobj(open(tempFileName, 'r'), self.out_file_for_raw_data)```

temporary files are created that are afterwards concatenated. However, shutil consistently misses some characters. The original temporary files are fine. This is very strange.
