### ISSUE TITLE
computeMatrix - outFileSortedRegions

### ISSUE THREAD

**Issue by simjbaum** [fidelram/deepTools#244]
Dear deepTools team,
thank you for providing such a nice software.

I have the following issue with the computeMatrix tool. I used this tool to compute the coverage over a given region  by adding the parameter outFileSortedRegions. Recently I updated to deeptools 2 and ran now the computeMatrix command. Unfortunately I got "genes" in the last column back, but no occupancy value for the respective region. 

The command:

for f in ~/Bioinformatics/chipseq/MSC/bamCoverage/* ; do computeMatrix reference-point --referencePoint TSS --regionsFileName ~/Bioinformatics/generegions/MSCTSSregion_RNAseqOverlap20160125.bed --scoreFileName "$f" --beforeRegionStartLength 25 --afterRegionStartLength 1500 --sortRegions no --averageTypeBins mean --numberOfProcessors 2 --binSize 25 --sortRegions no --outFileName "$f.matrix" --outFileSortedRegions "$f.bed" ; done

head of the regionsFileName
chr1	11873	11874	DDX11L1	uc001aaa.3	+
chr1	69090	69091	OR4F5	uc001aal.1	+
chr1	321083	321084	DQ597235	uc001aaq.2	+
chr1	321145	321146	DQ599768	uc001aar.2	+

head of the outFileSortedRegions
chr1	11873	11874	DDX11L1	uc001aaa.3	+	genes
chr1	69090	69091	OR4F5	uc001aal.1	+	genes
chr1	321083	321084	DQ597235	uc001aaq.2	+	genes
chr1	321145	321146	DQ599768	uc001aar.2	+	genes

Best wishes,
Simon

**Comment by dpryan79** [comment]
Try the `--outFileNameMatrix` option :)

**Comment by simjbaum** [comment]
OK. This would work also, however before I was getting, I think a calculation (e.g. mean) over all bins (or rows) back. Like this:

chr1	8384389	8404227	region_0	0.990655573603	+
chr1	8390197	8404227	region_1	0.968249455065	+
chr1	19969722	19984949	region_2	1.55951189274	+

Its just a minor thing, however it cut that step in calculating the one value over all values in that row. It was helpful :-) .

**Comment by dpryan79** [comment]
Good to know, we'll keep that in mind.

**Comment by fidelram** [comment]
we removed this functionality because 1. it was not documented,  2. users were expecting to get the same bed file after `--outFileSortedRegions ` to do other analysis. Previously, computeMatrix replaced the bed score column;  however, such column could contain useful information that was deleted. 3. there is a work around: select `--afterRegionStartLength`,  `--beforeRegionStartLength` and `--binSize` in such a way that you only get one bin. The result that you will get using `--outFileNameMatrix` is very similar to the behavior that you want.
