### ISSUE TITLE
Jbrowse are not able to open bigwig from bamCoverage 2.0.1

### ISSUE THREAD

**Issue by lelouar** [fidelram/deepTools#256]
Hi,

the new version of bamCoverage make bigwig that can't be oppened by Jbrowse. I try to use bigWigToBedGraph and BedGraphToBigWig from ucsc tools and open the new bigwig. And is oppenable with Jbrowse. I really don't know why. I have uploaded the two test file on my deeptools.galaxy instance to allow you to check the file and the differences. I subset the bigwig to just have the region 1:10000:100000 (chr:start:end) to have a smaller file.

The error in Jbrowse was: 
RangeError: argument 2 accesses an index that is out of range

(and it's for this reason that I tried to subset my bigWig but unfortunately the error was the same)

In an other hand IGB, IGV and your galaxy genome browser instance can open the two files.

I hope that you can see the differences between the two file that I uploaded on your galaxy instance,
thx,

Raoul

**Comment by dpryan79** [comment]
Presumably Jbrowse relies on some peculiarity on UCSC produced bigWig files. I'll have a look.

**Comment by dpryan79** [comment]
I just tried two of our test files and Jbrowse didn't have any issues with them. Perhaps you can send me some files that don't work. Otherwise I won't be able to track down the issue you're running into. I should note that I just used the version on the jbrowse.org home page. I supplied it with two of the test files from our public Galaxy instance and a multifasta file with chromosomes 19 and X from the GRCh37 reference.

**Comment by dpryan79** [comment]
Nevermind, I was just able to reproduce the issue.

**Comment by lelouar** [comment]
have you seen my uploaded files on deeptools.ie-freiburg.mpg.de ? my acount is raoul.raffel AT igh.cnrs.fr

**Comment by dpryan79** [comment]
I don't make a habit of looking at user's histories :)

Thanks for uploading those files, I'm having a look. My guess is that this is a JBrowse bug, since the other browsers work, but perhaps I have a remaining issue in libBigWig.

**Comment by lelouar** [comment]
I check the two file with biodalliance genome browser (http://www.biodalliance.org/) and the issue was the same. But it may be possible that the two genome browser use the same javascript library. I will check others new browser based on html5 and javascript library to see if one of them can use the two bigwig files.

**Comment by dpryan79** [comment]
I found the source of this. Jbrowse (and biodalliance, since they share code) assumes that the bigWig summary information, if present, is within the first 512 bytes of the file. This happens to be the case for files made by UCSC, but may or may not be for those made by anything else. I suppose I could change the order of the sections in libBigWig, but this is really a bug in these browsers. I would much prefer that the browsers be fixed, since they're the ones not following the bigWig format.

**Comment by dpryan79** [comment]
On second thought, this is such a trivial thing to change and I fully suspect that this javascript is heavily copy/pasted into other browser that I'll be forever filing bug reports if I don't just modify libBigWig. I'll just do that real quick.

**Comment by dpryan79** [comment]
There's now a `libBigWig-0.1.4` branch of pyBigWig. I did a quick test and Jbrowse is now perfectly happy with newly produced files. If you're using the command line version of deepTools, try `pip install git+https://github.com/dpryan79/pyBigWig.git@libBigWig-0.1.4 --user`, which will upgrade pyBigWig to use this. Reopen this or post an issue on the pyBigWig page if that doesn't solve the issue for you. I need to test this with IGV and some deepTools functions to ensure that nothing breaks, but the odds of that are near 0 :)

**Comment by dpryan79** [comment]
BTW, I'll make a new pyBigWig release after sufficient testing. The Galaxy tool will get updated sometime thereafter.
