### ISSUE TITLE
plotHeatmap with hierarchal clustering shouldn't die on fewer clusters

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#280]
Currently, if the --hclust option is used an one cluster gets no members then the BED file is written but plotHeatmap then completely fails. This failure to create the plot should be fixed. plotProfile seems to be OK with this, strangely.

Additionally, we need to add a bigger warning to the galaxy wrapper about this option.

**Comment by dpryan79** [comment]
I would suggest pushing the next release after this is solved.

**Comment by fidelram** [comment]
Probably it fails in the plotHeatmap because there is a constraint for the minimal numbers of elements in the cluster. This check is not in plotProfile. Without this check, small clusters trigger an exception in matplotlib because they are too small to plot.

**Comment by vivekbhr** [comment]
@fidelram yah that's the reason, since i can get a (bit uglier) plot when I turn it off.. So another alternative could be to remove this check and replace with a warning for the user to remove the small regions. But if this causes matplotlib to fail on certain occasions then we can remove the region and plot.
