### ISSUE TITLE
use several flagFilter in bamCoverage

### ISSUE THREAD

**Issue by lelouar** [fidelram/deepTools#316]
Hi,

Is it possible to implement the use of several filter based on flag ?

For example when we have paired-end data, we can imagine that we only need proper pairs. In that case we have to use several time samtools with -f 99, -f 147, -f 83 and -f 163, right ?

So if we can do this directly with deeptools it could be easier to processe paired-end data (and maybe a faster way to do this).

Once again, you do a very good jobs, 

thx

**Comment by dpryan79** [comment]
If you just want proper pairs then `-f 2` will work.

**Comment by lelouar** [comment]
yes I agree but I am reading a paper that use these 4 filter to keep only proper pair so I wondering if I missed something. Thx for the reply, I will investigate further and send a mail to the authors to better understand why they use this. This issue is maybe uninteresting. Sorry if it 's the case. thx

**Comment by fidelram** [comment]
For the case of filtering PE RNA-seq data by strand, complicated rules to
keep and skip flags  are necessary. That's why we added the
--filterRNAstrand option. However, in our documentation is an example on
how to do those complex flag queries:
http://deeptools.readthedocs.org/en/latest/content/tools/bamCoverage.html#separate-tracks-for-each-strand


fidel

On Fri, Mar 11, 2016 at 11:28 PM, lelouar <notifications@github.com> wrote:

> yes I agree but I am reading a paper that use these 4 filter to keep only
> proper pair so I wondering if I missed something. Thx for the reply, I will
> investigate further and send a mail to the authors to better understand why
> they use this. This issue is maybe uninteresting. Sorry if it 's the case.
> thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fidelram/deepTools/issues/316#issuecomment-195581981>.
>



-- 

Fidel Ramirez

**Comment by dpryan79** [comment]
I'm going to close this for now. If someone comes up with a really compelling use case then we could easily enough implement this, though. I would generally caution people from going too crazy with inclusion/exclusion flags, it's a good way to throw out perfectly good data.
