### ISSUE TITLE
plotCoverage: error when selecting invalid chromosome names 

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#321]
Selecting an illegal chromosome name (e.g. "chr19" instead of "19") throws an error. 
Probably other tools behave similarly. In this case an empty coverage plot would probably be more meaningful. Or should we aim for replacing 19<->chr19 automatically? The latter would be difficult in general. I have seen maps such as:
chrM <-> MT  
21 <-> Y
22 <-> X

**Comment by dpryan79** [comment]
Where possible we can add/remove `chr` (chrM <-> MT is always a special case), since we're mostly doing this already. 21 <-> Y should never be expected to work anywhere and should always throw an error.

As a design principal, it is always better to throw an error and abort than to create an empty file or meaningless file.

**Comment by dpryan79** [comment]
This is now implemented in the `develop` branch, which will become the 2.3 release.
