### ISSUE TITLE
Feature request: Plot or profile only using chosen samples and regions from computeMatrix results

### ISSUE THREAD

**Issue by MichaelMW** [fidelram/deepTools#326]
Maybe I missed something here, but is it possible to add a flag to plot only chosen samples and/or regions?
Something like this:
[--regionsToUse REGIONSLABEL [REGIONSLABEL ...]]
[--samplesToUse SAMPLESLABEL [SAMPLESLABEL ...]]
Whereby default is set to use all regions and samples. 

It's relatively simple to implement.
But it's very important, as it gives user the freedom to chose which part of the results needs to be plotted. 
Otherwise users are forced to run computeMatrix again which takes so much more time and resources to run than plotHeatmap.

**Comment by friedue** [comment]
Hi Michael,
historically, computeMatrix would accept only one sample, so the need to exclude samples never occurred until deepTools2.  deepTools2, on the other hand, has seen a significant increase in parameters and we're rather hesitant to add even more, especially if there's a simple work-around available (in your case, re-running computeMatrix).
For the particular parameter that you are proposing, I would be even less inclined to support its addition because the clustering, for example, is applied on the entire data set and the results will represent the clustering based on the signal from all data points that were supplied to computeMatrix. Allowing users to remove samples from the visualization done by plotHeatmap but still allowing for clustering across all samples (or even selected ones) is violating our aim to make analyses as transparent and reproducible as possible (in addition to complicating the settings even further).
Although it may present an annoying overhead, I would always recommend to re-run computeMatrix and plotHeatmap/plotSummary with the samples you're actually going to show in the end. This is the only way to know for sure the provenance of the data underlying the pretty image.

But let's see what the others have to say here!

**Comment by dpryan79** [comment]
I agree with @friedue, this is an unusual enough thing that I'd prefer people to just rerun things rather than adding "yet another option". deepTools has too many options as is.

**Comment by dpryan79** [comment]
@MichaelMW  I decided to put together a little script that can be used to subset the output of computeMatrix by sample/region. That'll create a new file, but is easier to support in general than "yet another deepTools option". You can download the script [here](https://github.com/fidelram/deepTools/blob/feature/subsetMatrix/scripts/subsetMatrix). I've not done much in the way of testing, but it's likely to work correctly. You'll need deepTools installed to use this. I'll include this as an additional script in the 2.3.0 release, so it won't get installed by default but will be around in case people need it.
