### ISSUE TITLE
Steps for release 2.3

### ISSUE THREAD

**Issue by dpryan79** [fidelram/deepTools#348]
All of the features are currently in place for release of version 2.3 (code name: "close all the github issues"). We do need to update readthedocs with pages that cover the following topics:

 * [x] Blacklist regions
 * [x] Metagene summarization
 * [x] Read extension
 * [x] Unscaled regions
 * [x] Read offsets

I think that the nuances in the above warrant their own pages, ideally with some graphical examples. I'll essentially assign myself to write those, since I'm the one who implemented these features.

In addition:
 * [x] Internal testing, 1 month (longer if needed), ending May 27. We're already using python3 for this.

The target will by for a July 1 release date.

**Comment by friedue** [comment]
Let me know if and how I can help.
I wanted to work on the documentation this week anyway, so may as well join forces.

On Apr 25, 2016, at 6:30 AM, Devon Ryan <notifications@github.com<mailto:notifications@github.com>> wrote:


All of the features are currently in place for release of version 2.3 (code name: "close all the github issues"). We do need to update readthedocs with pages that cover the following topics:

  *    Blacklist regions
  *    Metagene summarization
  *    Read extension
  *    Unscaled regions

I think that the nuances in the above warrant their own pages, ideally with some graphical examples. I'll essentially assign myself to write those, since I'm the one who implemented these features.

In addition:

  *    Internal testing, 1 month (longer if needed), ending May 27. We're already using python3 for this.
  *    Testing on the public Galaxy instance, 1 month, starting mid/late May. This will continue to use python 2.

The target will by for a July 1 release date.

**Comment by vivekbhr** [comment]
I have some documentation changes in #354 . Maybe merge your doc changes with develop after my PR is merged, to avoid conflict.
