### ISSUE TITLE
plotCorrelation output svg dendogram error

### ISSUE THREAD

**Issue by lelouar** [fidelram/deepTools#350]
Hi,

when we make an svg image of the plotCorrelation (heatmap), the dendogram is reverted.

![image](https://cloud.githubusercontent.com/assets/10290456/14823482/024b9092-0bd3-11e6-8a3e-b725cfb2ecb3.png)

the png version is ok.

Maybe this issue is already done (I am still in 2.0.1-25-g697bb3d), sorry if it's the case.

thanks,
Raoul

**Comment by fidelram** [comment]
This is fixed on version 2.3 although we should also fixed in the master branch. Is such a silly issue.

I think scipy changed the way this was displayed at some point and that introduced the problem. 

@lelouar if you want to fix the problem yourself simply search for a file called `correlation.py` and change

`z_var = sch.dendrogram(y_var, orientation='right',`

by 

`z_var = sch.dendrogram(y_var, orientation='left',`

**Comment by dpryan79** [comment]
We'll release a bug fix version (2.2.4) to address this. I expect it'll be available everywhere tomorrow (I'll close the issue once it is).

**Comment by dpryan79** [comment]
2.2.4 should be available via bioconda shortly. @fidelram already posted it to pypi. Closing
