### ISSUE TITLE
do clustering only based on specific samples

### ISSUE THREAD

**Issue by AlicePsyche** [fidelram/deepTools#374]
Hi, 

I have four samples to do heatmap but I only want to do clustering based on two of them and then "map" the corresponding columns in the other two samples. How can I achieve this using deeptools? Or the option where I could specify the column order ?

Thanks in advance.

**Comment by dpryan79** [comment]
There's currently no built-in way to do this. What you'll need to do is:

1. Run computeMatrix on the two samples you want to cluster with.
2. Cluster those, making sure to output a BED file with the regions.
3. Put that BED file into computeMatrix, this time specifying all of your samples.

Since the BED file output by step 1 contains the cluster names for each of the entries, computMatrix in step 3 will then honour that and the resulting heatmap/profile will be grouped according to the clusters you want.

**Comment by AlicePsyche** [comment]
Oh, I see. Thanks ! I would give it a try.
