### ISSUE TITLE
2.3.3 : ComputeMatrix removes missing data by default

### ISSUE THREAD

**Issue by vivekbhr** [fidelram/deepTools#402]
Regions with missing data are removed by computeMatrix in version 2.3.3 by default..

My random_clusters.bed has 500 regions.
With 2.2 :
```
$/package/deeptools-2.2.2/bin/computeMatrix  \
scale-regions -a 1000 -b 1000 -p 20 -o test-2.2.npz \
-R random_cluster.bed -S ${bw} \
--outFileSortedRegions test.cm22.bed

$wc -l test.cm22.bed
501 
```

With 2.3 :
```
$/package/deeptools-2.3.3/bin/computeMatrix  \
scale-regions -a 1000 -b 1000 -p 20 -o test-2.3.npz \
-R random_cluster.bed -S ${bw} \
--outFileSortedRegions test.cm23.bed

$wc -l test.cm23.bed
3
```

**Comment by dpryan79** [comment]
In the example BED file you gave me, there are only 13 entries inside the actual genome. Since the parallelization works by dividing the genome into chunks and then processing the BED regions in each, those illegal regions will never be encountered. Garbage in garbage out.

**Comment by vivekbhr** [comment]
You mean only 13 intervals are inside the chromosome lengths in dm6?

**Comment by dpryan79** [comment]
According to the bigWig files, yes.

**Comment by dpryan79** [comment]
Of course if the bigWig files aren't reporting the correct chromosome sizes then that's a different issue.

**Comment by dpryan79** [comment]
import pyBigWig
    f = open("random_cluster.bed")
    bw = pyBigWig.open("H3K9me2_merged.bw")
    total = 0
    bad = 0
    for line in f:
        total += 1
        cols = line.strip().split("\t")
        if int(cols[1]) >= bw.chroms(cols[0]):
            bad += 1
    print("{} of {} entries are bad".format(bad, total))
    f.close()

**Comment by vivekbhr** [comment]
ok.. I just checked that and found that after bedtools shuffle the new regions indeed extend chromosome boundaries. This wasn't supposed to be the case, since I wasn't using `-allowBeyondChromEnd`. http://www.clipular.com/c/6040333485342720.png?k=c_Ey9-DepsyoCQEu7us5gEj-F9U .

But why using or not using `--skipzeros` has no effect in this case, while in v2.2 i get different results?

**Comment by dpryan79** [comment]
The way that multithreading was handled in computeMatrix changed in version 2.3. Previously, everything except computeMatrix used the mapReduce submodule for multithreading. It was sort of annoying to add features like blacklist regions and what not, then, since there were multiple places that things needed to be changed. In 2.3, I modified computeMatrix to use the mapReduce submodule like everything else (lower maintainance overhead!).

In the pre-2.2 computeMatrix, it went through BED files one line at a time and made an internal list of all of the regions. It then split those up and ran the computations accordingly. Everything else read files into an interval tree, then chopped the genome into regions, and used those regions for multithreading. When a BED file was used with that, the regions in each genomic chunk were processed by a processor. Since a genomic chunk is bounded by the chromosome names and sizes in the bigWig and BAM files, the mapReduce submodule has always ignored regions that were completely outside of those bounds. But since computeMatrix wasn't using that it queried files with intervals that could never possibly exist.

This sort of behavior was present in everything except computeMatrix before 2.3, but is now present everywhere.

As an aside, the other result of this change is that the order of regions in a BED file are no longer preserved, which was sort of a side-effect of the pre-2.3 way computeMatrix worked (since the order of regions are now shuffled before being sent out for processing, there are a couple levels at which this has changed in 2.3).

**Comment by vivekbhr** [comment]
ok it's not a deepTools issue.. I am closing it..
