### ISSUE TITLE
Binning algorithm

### ISSUE THREAD

**Issue by annaquaglieri16** [fidelram/deepTools#409]
Hi, 
I would like to better understand the way bamCoverage and plotProfile/computeMatrix work. If I create a bigwig coverage file using 200bp bins, when I plot for example the coverage around TSS +- 2kb the profile plot seems to have been further smoothed since I do not see only 20 data points (200bp counts within 4kb window)  but I see a more detailed plot. 
Could you explain how you create the plot?

Thanks for your help, 
Anna

I attached an example below

[Profile_SC_H3K14ac_gc_genesTSS_not_scaled_std_400.pdf](https://github.com/fidelram/deepTools/files/431865/Profile_SC_H3K14ac_gc_genesTSS_not_scaled_std_400.pdf)

**Comment by dpryan79** [comment]
Hi Anna,

The binning is initially done across the genome when the bigwig file is created. So you'll have a bin for base 1 through 200, and then one for 201 through 400 and so on. computeMatrix is then looking at the 2kb on either side of each TSS in the bigwig file. When it does that, it redoes the binning. Let's take a smaller example, for the sake of simplicity. Suppose you have a TSS at position 50 and are interested in the 10 bases on either side. Further you have a bigwig file with 25 base bins and the following data:

    chr1    0    25    1.0
    chr1    25    50    2.0
    chr1    50    75    3.0

So let's see how computeMatrix will deal with that. First, it'll look for the values from position 40 through 60 (not inclusive). It'll make a vector of the following values:

    2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0

Given that, computeMatrix then rebins things according to the `-bs` option. This defaults to 10, so you'll end up with two bins: `2.0` and `3.0`. This is also why you see higher granularity in your plots, since you'll plot 400 points as opposed to 40.

I hope that clears things up.

**Comment by annaquaglieri16** [comment]
Yep, it's clear now!
Thanks a lot :)

Anna

**Comment by annaquaglieri16** [comment]
Hi, 
I have a question about how the profile plots are made for genes on different strands. If I provide a bedfile like this:

Chr    Start      End 		Strand 
chrM     1094     2675      +   
chr9     78175302 78175633      -    
chr14    50807447 50807771      -    
chr4    43492785 43493059      -

where the Start is always lower than End which means that for negative stranded genes the Start and End are reversed, would deepTools take the Strand information into account if I want to create profile plots around the TSS? Or will it plot TES for negative genes instead?

Thanks for your help, 

Anna

**Comment by dpryan79** [comment]
Deeptools will respect the strand, so you'll only get TSS. 

Devon

**Comment by annaquaglieri16** [comment]
Thanks Devon! 
And does the Strand need to be in the 6th column of the bed file or a structure as I showed above is ok?

Anna

**Comment by dpryan79** [comment]
It'll need to be in column 6, sorry I missed that.
