### ISSUE TITLE
computeMatrix: use reference-point and scale-regions modes at the same time

### ISSUE THREAD

**Issue by AlicePsyche** [fidelram/deepTools#411]
Hi, 

I am wondering is it possible to use reference-point and scale-regions modes at the same time? For example, I want to plot K4me3 signals around TSS(reference-point) and I also want to plot K36me3 signals span gene body(scale-regions). In R, I usually map the gene body signals to its corresponding TSS signals,  plot heatmap separately but I love your `plotHeatmap`, more beautiful :) So how can I do this in deeptools? 

Thanks in advance ~

**Comment by dpryan79** [comment]
There's no direct way to do this with the full deepTools tools, but you can if you use `subsetMatrix`, from the `scripts/` directory. In essence, you run `computeMatrix` separately for your two signal and the use `subsetMatrix cbind` to merge the resulting files. While the heatmaps will be correct, note that the x-axis ticks will be incorrect and in the wrong place. The data is fine, but there's only one x-axis labeling system used for everything, so if the left-most heatmap is 1kb on either side of the TSS then those labels will also be used for the scale-regions heatmap. The plots are otherwise correct, just ignore the ticks and their labels.

BTW, there are plans to make `subsetMatrix` a full tool for the 2.4 release (see #393).
