### ISSUE TITLE
bamCompare: --scaleFactors c1:c2

### ISSUE THREAD

**Issue by your-highness** [fidelram/deepTools#414]
Dear deepTools developers,

I would like to calculate a control-normalized coverage using bamCompare with `--ratio substract`. I thought using ``--scaleFactorsMethods readCount`` is appropriate in this case. However, the resulting bigWigs seem not to be subtracted for the readCount scaled Input (see below)

When using `--scaleFactorsMethods SES` I get the error (even when increasing `-l`):
```
*ERROR*: The median coverage computed is zero for sample(s) #[1, 2]
```

In my case the Input to Treatment coverage ration in "background" regions is `~1:0.05`. Thus, I used the following command:
```
bamCoverage -b1 treatment.bam -b2 control.bam -o out.bw --scaleFactors 1:0.05
```
This gives me a good assessment of the difference:
![The difference between Input and Treatment is correctly calculated when giving explicit scale factors. Using ``--scaleFactorsMethods readCount`` is giving a non-library size scaled difference.](https://cloud.githubusercontent.com/assets/1949888/18168042/1124dc96-7054-11e6-9a90-e078f0994bac.png)

Question:
1. _The order of the `--scaleFactors` is inverted with respect to the given bam files, _i.e._ c1 scales bamfile2 and c2 scales bamfile1.
2. _Do you think this ad-hoc approach is correct? Why does ``--scaleFactorsMethods readCount`` not correct for this (because of the enriched Regions?_

**Comment by dpryan79** [comment]
The order of the scale factors is correct, it's just that the signal is multiplied rather than divided by them.

Regarding `--scaleFactorsMethods readCount`, can you use the verbose option and see what the computed normalization factors are? My guess is that the huge peaks (these should presumably be blacklisted) are mucking that up.

**Comment by your-highness** [comment]
Hi @dpryan79 

Regarding `--scaleFactors`: At first sight, `1:0.05` implies that treatment is left as is and control is multiplied by 0.05. However, the inverse is the case for my example above.

Regarding `--scaleFactorsMethods readCount`: The estimated scale factor are 1:0.043 which seems correct
```
genome partition size for multiprocessing: 1000000
using 8 processors for 2744 number of tasks
genome partition size for multiprocessing: 1000000
using 8 processors for 2744 number of tasks
Size factors using total number of mapped reads: [ 1.         0.0434697]
Scale factor for RPKM is 168.404034961
Individual scale factors are [ 168.40403496    7.32047273]
PoolWorker-18,  processing 3190 (8209.5 per sec) reads @ chr5:120214000-120618903
PoolWorker-18,  processing 236768 (41608.7 per sec) reads @ chr5:120214000-120618903
PoolWorker-18 countReadsInRegions_worker: processing 8098 (1310.3 per sec) @ chr5:120214000-120618903
PoolWorker-17,  processing 9234 (7723.5 per sec) reads @ chr5:119214000-120214000
PoolWorker-17,  processing 611776 (32869.1 per sec) reads @ chr5:119214000-120214000
PoolWorker-17 countReadsInRegions_worker: processing 20000 (998.0 per sec) @ chr5:119214000-120214000
```

**Comment by dpryan79** [comment]
I've double checked and confirmed that `bamCompare` is doing the correct thing. If you zoom into a specific bin and count the number of reads, then those multiplied by the "Individual scale factors", which are the final scaled values used, and then subtract the results then you'll get what's in the bigWig file. I suspect that this wasn't apparent since it's the "Individual scale factors" line that ends up being used, since it's the size factor multiplied by the RPKM or normalizedTo1x scaling factor.
