### ISSUE TITLE
computeMatrix: keep the original order as bed file

### ISSUE THREAD

**Issue by AlicePsyche** [fidelram/deepTools#418]
Hi, 

I am wondering is it possible that the computeMatrix output files could keep the original order as that in -R bed file? It seems that `--sortRegions=no` doesn't do the work. 

Thanks in advance!

**Comment by dpryan79** [comment]
Since version 2.3 deepTools reads one or more BED/GTF files into memory first and then starts the computation (prior to 2.3, everything except computeMatrix was already doing this, we just standardized on it for the 2.3 release). So the regions are output in more or less the order in which they happen to be stored in memory, rather than the order in your file, which makes for lower maintenance overhead. Consequently, `--sortRegions=no` is doing the right thing, just not what you expect given how the previous releases worked. For the 2.4 release I'm adding a new tool that can do things with the output of computeMatrix, like reorder the entries and subset or merge them. If the exact order matters to you then you'll be able to use that. You can follow the progress of that in #393. Once I've mentioned that the sorting part of that is done (I'm hoping to finish that today, in fact) then you can download the script and use it.
