### ISSUE TITLE
error using example for computeMatrix and plotHeatmap

### ISSUE THREAD

**Issue by jocelynnpearl** [fidelram/deepTools#441]
Hello,

I am trying to use computeMatrix and plotHeatmapper to generate heatmaps from some ChIPseq data.  I have my bigWigs and feature maps, and yesterday I was able to generate the .gz matrix file to input into plotheatmap:

`plotHeatmap -m matrixresult.gz --colorList white black --heatmapHeight 25 --heatmapWidth 3 --samplesLabel "TSS" -out OUTPUT.png --whatToShow 'heatmap and colorbar' --sortUsing max`

but then I received an error:

> ... makeMappingArray
>     "data mapping points must start with x=0. and end with x=1")
> ValueError: data mapping points must start with x=0. and end with x=1

Today I thought I would start with your example file - but this is getting hung up on the first step, computeMatrix.
# i tried this after downloading your .bed and .bigWig example files from here: (http://deeptools.readthedocs.io/en/latest/content/example_gallery.html#normalized-chip-seq-signals-and-peak-regions
)

`computeMatrix reference-point -S DNase_mouse.bigwig -R Whyte_TypicalEnhancers_ESC.bed --referencePoint center -a 2000 -b 2000 -out matrix_Enhancers_DNase_ESC.tab.gz`

# error output

> Preloading the following deepBlue files: DNase_mouse.bigwig
> Traceback (most recent call last):
>   File "/Users/Jocelynn/anaconda/bin/computeMatrix", line 11, in <module>
>     main(args)
>   File "/Users/Jocelynn/anaconda/lib/python2.7/site-packages/deeptools/computeMatrix.py", line 405, in main
>     res = list(map(db.preloadWrapper, deepBlueFiles))
>   File "/Users/Jocelynn/anaconda/lib/python2.7/site-packages/deeptools/deepBlue.py", line 114, in preloadWrapper
>     res = deepBlue(foo[0], url=args.deepBlueURL, userKey=args.userKey)
>   File "/Users/Jocelynn/anaconda/lib/python2.7/site-packages/deeptools/deepBlue.py", line 140, in __init__
>     raise RuntimeError("The requested sample({}) has no associated experiment!".format(sample))
> RuntimeError: The requested sample(DNase_mouse.bigwig) has no associated experiment!

Any help is appreciated!

**Comment by dpryan79** [comment]
Hi Jocelynn, can you send one of us the file produced by computeMatrix? We can then debug what's happening there (you can just send it to ryan@ie.freiburg.mpg.de).

Regarding the error with DNase_mouse.bigwig, apparently the file doesn't exist or is somehow misspelled. When deepTools is given a file name that doesn't exist, it assumes that it's a file hosted on deepBlue. I should work on a proper error message for that in the next release, since there's no way anyone but me could tell that from the stack trace.

**Comment by jocelynnpearl** [comment]
You're correct - the bigwig file, when downloaded, get's called something besides the example script name "wgEncodeUwDnaseEscj7S129ME0SigRep1.bigwig" vs "DNase_mouse.bigwig" in your script.  I should have caught that but you might want to update it to make it easier for future tests.

I've emailed you my matrixresult.gz file - let me know if you find the issue!

**Comment by dpryan79** [comment]
Got it, thanks. The problem was the space in `--colorList white black`. That should be `--colorList white,black`. We should change how that's parsed so it throws a coherent error message if the right format isn't used. I'll leave this issue open until that and the previously mentioned completely unintelligible stack trace are resolved, thanks for reporting these!

**Comment by jocelynnpearl** [comment]
Perfect - that resolved the problem.  Thank you!

**Comment by brianpenghe** [comment]
I got the same error message when running computeMatrix. The real cause turned out to be that the .bw file couldn't be found at that path (file name typo).

**Comment by gtrichard** [comment]
Still existing in `computeMatrix`

**Comment by dpryan79** [comment]
Any time the file doesn't exist it will be queried on epiBlue, since I have no way to know if users have made a typo or are specifying a sample ID.

**Comment by Moxsf** [comment]
The file name was inputted wrong which suffix is <.bigWig>. (W is a capital letter)
