### ISSUE TITLE
plotProfile line thickness

### ISSUE THREAD

**Issue by igordot** [fidelram/deepTools#473]
Is it possible to change the line thickness or shape (dashes, dots, etc.) in plotProfile? If not, is it possible to add that option?

**Comment by fidelram** [comment]
We try to keep a balance between customization and simplicity. Because of this, we try to avoid  from adding new parameters if possible. 

I could suggest a few workarounds to change the line widths: 

a) modify your matplotlitrc file (see http://matplotlib.org/users/customizing.html). 
b) change this line in the code https://github.com/fidelram/deepTools/blob/master/deeptools/heatmapper_utilities.py#L67 and add the thickness and shape required. 
c) use the `--outFileNameData` to save the data for the plot and used other program to plot the values. 
d) save the plot as pdf or svg and edit it with inkscape or illustrator.

**Comment by igordot** [comment]
Thanks for clarifying and the suggestions.
