### ISSUE TITLE
plotEnrichment fails on long sample names

### ISSUE THREAD

**Issue by thomasmanke** [fidelram/deepTools#526]
... because it cannot plot the within the default device sizes.

Possible solutions
i) trimming name
ii) reporting error properly (currently it says something like bottom >=top)
iii) optionally switch off plot (--> as for plotFingerprint in develop)

**Comment by dpryan79** [comment]
The only real options are:

1. Don't plot anything (already implemented for 2.5.1, which will hopefully come out next week friday)
2. Allow people to adjust the plot size, which we should probably do anyway since I just allowed that for almost everything else.

We have no way of determining what will actually fit on the plot, that's all up to matplotlib. I'll close this once I've implemented `--plotWidth` and `--plotHeight`.

**Comment by thomasmanke** [comment]
2. is implemented already, but users will have to know that this is the reason. The current error does not suggest it.

**Comment by dpryan79** [comment]
Oh, plotEnrichment, you can already change the width and height, though I can make the plot optional too.

**Comment by dpryan79** [comment]
This is now implemented in `feature/implement256`.

**Comment by dpryan79** [comment]
@thomasmanke There's no way for us to change the error, it's not our code.

**Comment by dpryan79** [comment]
@thomasmanke This is now in the `develop` branch. Please `module load deeptools/develop` in a few minutes and try plotEnrichment without specifying a plot.
