### ISSUE TITLE
binsize default 10 in computeMatrix, 50 in bamcompare/bamcoverage

### ISSUE THREAD

**Issue by endrebak** [fidelram/deepTools#545]
If you have a bin size of 50 in your bws, does it help the resolution to have a bin size of 10 in your computematrix call? I guess the resolution will be 50 either way. If so you might want to change the defaults.

**Comment by dpryan79** [comment]
The bins here aren't necessarily the same things. Particularly with the `scale-regions` options, the bin size for a given transcript/feature may refer to 10 bases, or 20 or many many more bases on the genome, due to scaling. Effectively what this does is just sets the number of bins in which the average/median/whatever is calculated in each feature.
