### ISSUE TITLE
`multiBamSummary` fails with `cpython-36m-x86_64-linux-gnu.so: undefined symbol: hasEntries`

### ISSUE THREAD

**Issue by holgerbrandl** [fidelram/deepTools#618]
I struggle to to run deeptools (and `multiBamSummary` in particular) under linux. Here's a short docker setup to reproduce the error:

```
docker pull python
docker run -it python bash

# in container
> pip3 install deeptools

> multiBamSummary
Traceback (most recent call last):
File "/usr/local/bin/multiBamSummary", line 4, in <module>
from deeptools.multiBamSummary import main
File "/usr/local/lib/python3.6/site-packages/deeptools/multiBamSummary.py", line 9, in <module>
import deeptools.countReadsPerBin as countR
File "/usr/local/lib/python3.6/site-packages/deeptools/countReadsPerBin.py", line 13, in <module>
import pyBigWig
ImportError: /usr/local/lib/python3.6/site-packages/pyBigWig.cpython-36m-x86_64-linux-gnu.so: undefined symbol: hasEntries
```

What am I doing wrong?

**Comment by dpryan79** [comment]
Oh no, I made a small error in the most recent pyBigWig release. For the moment, you can get around this by uninstalling pyBigWig (`pip uninstall -y pyBigWig`) and then reinstalling it with `pip install --no-cache-dir pyBigWig`.

The problem is caused by me accidentally putting the `hasEntries()` function in a block of code that only exists if numpy is installed. If `pip install deeptools` installs numpy before pyBigWig then everything works correctly, but if it installs pyBigWig first then you get this error. I'll quickly push out a new version of pyBigWig to fix this!

BTW, if you want docker versions of tools, I suggest the biocontainers project. Since I put deepTools in bioconda there's automatically a docker container built that will work properly (I have pyBigWig depend on numpy in bioconda).

**Comment by dpryan79** [comment]
I just made pyBigWig version 0.3.6 available, so this should now be fixed. Sorry about that!

**Comment by holgerbrandl** [comment]
This was amazingly fast. Thanks a lot for your help. Works great now.
