### ISSUE TITLE
heatmapper: Group {} contains too few regions {}. It can't be plotted.

### ISSUE THREAD

**Issue by M4CC4M** [fidelram/deepTools#85]
Hello,

I can't find anywhere that mentions the minimum number of regions allowed per group.
Is there any doc. that mentions how this limit is calculated and why it is there?

Thanks for the v.great tools!

**Comment by fidelram** [comment]
The minimum number of regions allowed per group depends on the total number of regions. Roughly, if a group contains 0.1 percent of the total regions it can't be plotted because it would be too thin. The restriction comes actually from the matplotlib library. 

A workaround for this is to decrease the total number of regions by subsampling large groups or to use the profiler instead of the heatmapper, but of course in this second case only the meta profile is shown.
